name: lint
on:
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/checkout@v4
    - run: npx --package @biomejs/biome -c 'biome ci src examples'
